from handlers import admin_panal
from handlers import biography
from handlers import buizness
from handlers import casino
from handlers import crypto_exchange
from handlers import magazin
from handlers import map
from handlers import menu
from handlers import promocodes
from handlers import request_to_moderator
from handlers import school
from handlers import workers
from handlers import start